### ISSUE TITLE
Python BCubed broken due to float cast

### ISSUE THREAD

**Issue by RunOrVeith** [m-wiesner/BCUBED#2]
Numpy can not compute several operations when casting the following to `float`
in `compute_class_precision_recall`, e.g. `np.tile` results in `TypeError: 'float' object cannot be interpreted as an integer`:

```python
  num_elements = float(len(L))
  num_labels   = float(L.max() + 1)
  num_clusters = float(K.max() + 1)
```

Simply not doing that solves the issue (at least the code runs):

```python
  num_elements = len(L)
  num_labels   = L.max() + 1
  num_clusters = K.max() + 1
```

**Comment by m-wiesner** [comment]
Thanks for catching this. I don't remember why I cast those values to floats, but everything seems to run when I remove it, so I will merge this.

**Comment by RunOrVeith** [comment]
Sure, no problem. I guess it would make sense to also give it a version bump on pipy.
